include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - riverpod_lint

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_use_package_imports: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    unawaited_futures: true
    avoid_print: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    public_member_api_docs: false